-- ── GIN index for e-tag containment lookups ──────────────────────────────────
-- The channel-window aux closure (bridge.rs handle_channel_window_filter) and
-- every other #e fan-out resolve "events targeting these rows" with JSONB
-- containment: tags @> '[["e","<hex>"]]', OR-ed once per retained row. With no
-- index over `tags`, each hop bitmap-scans every events partition on the
-- (community_id, kind, ...) btree and filters ~100k rows to find a handful —
-- measured ~900ms per hop on staging, two sequential hops per scroll-back
-- page (~1.7s of the ~2.1s per-page total; RESEARCH/PERF_STAGING_SCROLLBACK).
--
-- jsonb_path_ops: smaller and faster than the default jsonb_ops, supports
-- exactly the @> operator — the only operator the query path uses
-- (event.rs e-tag pushdown).
--
-- Partitioned parent: CREATE INDEX recurses to all partitions and future
-- partitions inherit it. Built without CONCURRENTLY (not supported on
-- partitioned parents); on brownfield databases this takes a share lock per
-- partition while each partition's index builds — run during a deploy window.
--
-- Additive migration: previously applied files must not change checksum.

CREATE INDEX idx_events_tags_gin ON events USING GIN (tags jsonb_path_ops);
